name: Web Scraping Workflow

on:
  push:
    branches:
      - main
  # You can also trigger it on a schedule:
  schedule:
    - cron: "0 0 * * *"  # Run every day at midnight (UTC)

jobs:
  scrape:
    runs-on: ubuntu-latest  # This will run the script on a Linux VM
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # You can specify a version like 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your dependencies

      - name: Run the web scraping script
        run: |
          python scrape_posts.py  # Run your scraping script

      - name: Commit and push results (optional)
        run: |
          git config --global user.name 'GowerCampbell'
          git config --global user.email 'Gower.Campbell@gmail.com'
          git add LinkedIn-Posts.md  # If you're saving the result to a file
          git commit -m "Updated LinkedIn posts"
          git push
